// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leuumrlkhnbatuhzxmkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxldXVtcmxraG5iYXR1aHp4bWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MDkxNjcsImV4cCI6MjA3MDE4NTE2N30.3NH5RvAjp2KnXYa-dnstBZC31gV4eBXcxpvB_KPCq0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});